import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
// import styles from '../styles/Home.module.css'
import AddTransaction from "../components/AddTransaction";
import Balance from "../components/Balance";
import IncomeExpense from "../components/IncomeExpense";
import Transaction from "../components/Transaction";
import TransactionList from "../components/TransactionList";
import Link from "next/link";
import Expense from  '../styles/Expense.module.css';
import { useRouter } from "next/router";


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <div className="row">
              <AddTransaction />
              <TransactionList />
          </div>
            {/*<button onClick={redirect}>Click Me</button>*/}
            <div className="buttonContainer">
                <Link href="./summary"><button className="button">View Summary</button></Link>
            </div>

        </div>
      </main>
    </>
  )
}
